name: Build & Synchronization

on:
  push:
    branches:
      - 'master'
      - 'release-*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: GET Tools
        run: wget https://github.com/AliyunContainerService/image-syncer/releases/download/v1.3.0/image-syncer-v1.3.0-linux-amd64.tar.gz && tar -xzf image-syncer-v1.3.0-linux-amd64.tar.gz 

      - name: Synchronization
        env:
          AUTH: ${{ secrets.AUTH }}
        if: github.event_name == 'push'
        run: echo "$AUTH" > ./auth.json && .github/workflows/sync.sh
